/*
 * FiberMC API
 *
 * API documentation for FiberMC
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jp@jpcode.dev
 * Generated by: https://openapi-generator.tech
 */


use serde_repr::{Serialize_repr, Deserialize_repr};



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Author {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "mrSlug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mr_slug: Option<Option<String>>,
    #[serde(rename = "cfSlug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cf_slug: Option<Option<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Author {
    pub fn new() -> Author {
        Author {
            id: None,
            mr_slug: None,
            cf_slug: None,
            name: None,
        }
    }
}


