/*
 * FiberMC API
 *
 * API documentation for FiberMC
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jp@jpcode.dev
 * Generated by: https://openapi-generator.tech
 */


use serde_repr::{Serialize_repr, Deserialize_repr};

/// 
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum FiberCategory {
    Invalid,
    Technology,
    Adventure,
    Magic,
    Utility,
    Dimensions,
    Decoration,
    ApiAndLibrary,
    WorldGeneration,
    Storage,
    Food,
    Equipment,
    Miscellaneous,
    OresAndResources,

}

impl ToString for FiberCategory {
    fn to_string(&self) -> String {
        match self {
            Self::Invalid => String::from("0"),
            Self::Technology => String::from("1"),
            Self::Adventure => String::from("2"),
            Self::Magic => String::from("3"),
            Self::Utility => String::from("4"),
            Self::Dimensions => String::from("5"),
            Self::Decoration => String::from("6"),
            Self::ApiAndLibrary => String::from("7"),
            Self::WorldGeneration => String::from("8"),
            Self::Storage => String::from("9"),
            Self::Food => String::from("10"),
            Self::Equipment => String::from("11"),
            Self::Miscellaneous => String::from("12"),
            Self::OresAndResources => String::from("13"),
        }
    }
}

impl Default for FiberCategory {
    fn default() -> FiberCategory {
        Self::Invalid
    }
}




