/*
 * FiberMC API
 *
 * API documentation for FiberMC
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jp@jpcode.dev
 * Generated by: https://openapi-generator.tech
 */


use serde_repr::{Serialize_repr, Deserialize_repr};



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ForeignAuthorResponse {
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<crate::models::ForeignPlatform>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl ForeignAuthorResponse {
    pub fn new(name: String, slug: String) -> ForeignAuthorResponse {
        ForeignAuthorResponse {
            platform: None,
            name,
            slug,
        }
    }
}


