/*
 * FiberMC API
 *
 * API documentation for FiberMC
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jp@jpcode.dev
 * Generated by: https://openapi-generator.tech
 */


use serde_repr::{Serialize_repr, Deserialize_repr};

/// 
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum ForeignPlatform {
    Invalid,
    Modrinth,
    CurseForge,

}

impl ToString for ForeignPlatform {
    fn to_string(&self) -> String {
        match self {
            Self::Invalid => String::from("0"),
            Self::Modrinth => String::from("1"),
            Self::CurseForge => String::from("2"),
        }
    }
}

impl Default for ForeignPlatform {
    fn default() -> ForeignPlatform {
        Self::Invalid
    }
}




