/*
 * FiberMC API
 *
 * API documentation for FiberMC
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jp@jpcode.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModStatsResponse {
    #[serde(rename = "modId")]
    pub mod_id: uuid::Uuid,
    #[serde(rename = "modrinthStats")]
    pub modrinth_stats: Vec<crate::models::TimestampedModStats>,
    #[serde(rename = "curseForgeStats")]
    pub curse_forge_stats: Vec<crate::models::TimestampedModStats>,
    #[serde(rename = "overallStats")]
    pub overall_stats: Vec<crate::models::TimestampedModStats>,
}

impl ModStatsResponse {
    pub fn new(mod_id: uuid::Uuid, modrinth_stats: Vec<crate::models::TimestampedModStats>, curse_forge_stats: Vec<crate::models::TimestampedModStats>, overall_stats: Vec<crate::models::TimestampedModStats>) -> ModStatsResponse {
        ModStatsResponse {
            mod_id,
            modrinth_stats,
            curse_forge_stats,
            overall_stats,
        }
    }
}


