/*
 * FibermcApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "mrSlug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mr_slug: Option<Option<String>>,
    #[serde(rename = "cfSlug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cf_slug: Option<Option<String>>,
    #[serde(rename = "summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Option<String>>,
    #[serde(rename = "categories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Option<Vec<crate::models::FiberCategory>>>,
    #[serde(rename = "authors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authors: Option<Option<Vec<crate::models::Author>>>,
    #[serde(rename = "dateReleased", skip_serializing_if = "Option::is_none")]
    pub date_released: Option<String>,
    #[serde(rename = "dateModified", skip_serializing_if = "Option::is_none")]
    pub date_modified: Option<String>,
    #[serde(rename = "downloadCount", skip_serializing_if = "Option::is_none")]
    pub download_count: Option<i32>,
    #[serde(rename = "mcVersions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mc_versions: Option<Option<Vec<String>>>,
}

impl ModResponse {
    pub fn new() -> ModResponse {
        ModResponse {
            id: None,
            name: None,
            mr_slug: None,
            cf_slug: None,
            summary: None,
            categories: None,
            authors: None,
            date_released: None,
            date_modified: None,
            download_count: None,
            mc_versions: None,
        }
    }
}


