/*
 * FiberMC API
 *
 * API documentation for FiberMC
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jp@jpcode.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WeatherForecast {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "temperatureC", skip_serializing_if = "Option::is_none")]
    pub temperature_c: Option<i32>,
    #[serde(rename = "temperatureF", skip_serializing_if = "Option::is_none")]
    pub temperature_f: Option<i32>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

impl WeatherForecast {
    pub fn new() -> WeatherForecast {
        WeatherForecast {
            date: None,
            temperature_c: None,
            temperature_f: None,
            summary: None,
        }
    }
}


